### PR TITLE
Awareness

### PR DESCRIPTION
**Pull request by xyntechx**
This is the design testing the AI's awareness/responsiveness to a change in env as a signal by the human to indicate their preference

### CODE REVIEW

**Review by camall3n — COMMENTED** [review]
With this one, wouldn't the human always want to push the button?

**Comment by xyntechx** [comment]
Yep, it's based on the 3rd design I sent. What I'm hoping to test with this design is whether the AI will immediately go for the already-visible lower reward, or wait for the human to open the door (i.e. give it more info) so that it can get the initially-obstructed higher reward (i.e. react to the change in env as a signal that the human must want something from the room). The human will definitely always want to push the button, but what matters is whether the AI will wait for the human to do so before it assumes that the already-visible reward is the desired reward and goes for it. The human is also powerless to stop the AI once it has begun moving, unlike in `estop.py`. So to put it more concretely, this is testing info/capability asymmetry, where the human knows more about their preferences but cannot act on it, while the AI knows less about the human's preferences but can act on it (I read this paper on DoD recently which remotely inspired the design https://arxiv.org/pdf/2305.20076).

Having said that, please let me know if any design changes need to be made!

**Comment by camall3n** [comment]
I understand that in the human's mind, opening the door is signaling to the AI that there's something valuable in the room. But I don't understand how the AI would know that without some prior information, like knowledge about doors and rooms and typical treasure locations, etc.

Absent any communication with the human before the game begins, how would the AI know that the door opening is important?

**Comment by xyntechx** [comment]
Hmm I guess so. I was thinking that opening doors require a deliberate effort on the human's part, which may signal to the AI that the human wants something from the room. Although I guess we could argue that the human may be opening the door just for the sake of opening the door (like when the human is walking towards the door just for the sake of walking towards the door). Also the AI reacting to a change in env isn't really a simulation of a resource constraint, which is why I wanted #1 to replace this design when I shared it in Slack.

I do have some new ideas to simulate **limited attention** - I'll share it in Slack once I've fleshed them out!

We could close this PR if that works for you :))

**Comment by camall3n** [comment]
Okay, sounds good!

**Pull request closed without merging**
