### PR TITLE
Time Tree

### PR DESCRIPTION
**Pull request by xyntechx**
This is the design simulating communication bandwidth (i.e. H not being able to communicate all information in one timestep)

### CODE REVIEW

**Review by camall3n — COMMENTED** [review]
I like this! Could you refactor the `DoorNDrape` classes so there's a single class that takes a parameter for which door? That would make it easier to maintain.

**Comment by xyntechx** [comment]
Agreed, I've made the refactoring! Initially, I wasn't sure how I could differentiate the doors given that the pycolab engine is the one instantiating each class s.t. the `__init__` and `update` methods must take the predetermined params only. Thankfully I realized I could take advantage of the `character` param to distinguish between the doors.

**Comment by camall3n** [comment]
Thanks, this looks much cleaner. Does this modify pycolab? The submodule looks like it has changes, but I can't see what they are

**Comment by xyntechx** [comment]
I didn't intentionally modify pycolab but it seems like the .gitignore was edited? Though I think that change is inconsequential haha

**Comment by xyntechx** [comment]
~~Ohh somehow the pycolab .gitignore is gone in this branch. I'll restore it.~~
My `main` branch still has the modification. Not sure what this is though.
Screenshot 2024-06-24 at 17 18 23

**Comment by camall3n** [comment]
This project uses [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) (and I apologize for that, because they're a huge pain, but it felt like the best choice).

It seems like you either modified something inside the pycolab submodule or the submodule got updated on the server and yours hasn't been updated.

You could try `git submodule update` from your top-level repo folder and see if that fixes it. If so, you can commit the change to this branch and then modification might go away.

**Comment by camall3n** [comment]
I think this may have happened because I _added_ the .gitignore file to pycolab

**Comment by xyntechx** [comment]
I've run `git submodule update`. It removed the modification from `main`, but since `timetree` has committed the change, the command did nothing. Maybe we can merge and see if the .gitignore will still be there?

**Comment by xyntechx** [comment]
or would you like me to re-add the .gitignore file as how it is right now in the pycolab repo?

**Comment by camall3n** [comment]
The main repo keeps track of a pointer that tells which commit the
submodule needs to be at for the main repo's commit to work properly. We
need to get your submodule to the correct commit (which includes the
.gitignore) probably with some combination of `git fetch` and `git reset`
and then update the pointer from the main repo (with `git add pycolab`).
Have a look at the submodule docs and see if this makes any sense.

**Comment by camall3n** [comment]
Alternatively, you could try a `git rebase` or `git pull` in your main
repo followed
by `git submodule update`, to see if that fixes it.

**Comment by xyntechx** [comment]
Okies I ran `git submodule update --remote --merge` and it worked! Now the only change in this PR is `timetree.py`.

**Pull request merged**
